[project]
name = 'synths-on-stacks'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.sample-sip-010-token]
path = 'contracts/sample-sip-010-token.clar'
clarity_version = 1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
